### PR TITLE
Supports changing the package name of Bitnami.

### PR DESCRIPTION
**Pull request by MayaEnomoto**
The registry key was changed in Bitnami Redmine (since 4.2), so I added it to the code.
"Redmine Packaged by Bitnami"

### CODE REVIEW

**Comment by takuya-takeuchi** [comment]
@MayaEnomoto 

Thank you for your contribution!!
Could you change target branch from master to develop?
I will merge to master when I release.
Thank you.

**Review by takuya-takeuchi — APPROVED** [review]

**Comment by takuya-takeuchi** [comment]
@MayaEnomoto 

Oh, I forgot to change target branch by myself.
Ok, you need not to do more!!

**Comment by MayaEnomoto** [comment]
Thank you for your correspondence.

**Comment by takuya-takeuchi** [comment]
@MayaEnomoto 

We just released 1.9.2.0.
Thanks a lot and happy weekend!!

**Pull request merged**
